exports.accounts = require('./accounts')
exports.balance = require('./balance')
exports.blockNumber = require('./block-number')
exports.witnetPriceFeed = require('./witnet-price-feed')
exports.witnetRandom = require('./witnet-random')
exports.readSupraPriceFeed = require('./supra-price-feed')