/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { PlatformToken__factory } from "./PlatformToken__factory";
export { TestToken__factory } from "./TestToken__factory";
export { WKLAY__factory } from "./WKLAY__factory";
